name: rt_mo
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.6.2=py310h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py310h7f8727e_0
  - arrow-cpp=16.1.0=hc1eb8f0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py310h06a4308_0
  - aws-c-auth=0.6.19=h5eee18b_0
  - aws-c-cal=0.5.20=hdbd6064_0
  - aws-c-common=0.8.5=h5eee18b_0
  - aws-c-compression=0.2.16=h5eee18b_0
  - aws-c-event-stream=0.2.15=h6a678d5_0
  - aws-c-http=0.6.25=h5eee18b_0
  - aws-c-io=0.13.10=h5eee18b_0
  - aws-c-mqtt=0.7.13=h5eee18b_0
  - aws-c-s3=0.1.51=hdbd6064_0
  - aws-c-sdkutils=0.1.6=h5eee18b_0
  - aws-checksums=0.1.13=h5eee18b_0
  - aws-crt-cpp=0.18.16=h6a678d5_0
  - aws-sdk-cpp=1.10.55=h721c034_0
  - babel=2.11.0=py310h06a4308_0
  - beautifulsoup4=4.12.3=py310h06a4308_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - boost-cpp=1.82.0=hdb19cb5_2
  - brotli-python=1.0.9=py310h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.11.26=h06a4308_0
  - comm=0.2.1=py310h06a4308_0
  - cyrus-sasl=2.1.28=h52b45da_1
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.6.7=py310h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - exceptiongroup=1.2.0=py310h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.3=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.12.1=h4a9f257_0
  - gflags=2.2.2=h6a678d5_1
  - glib=2.78.4=h6a678d5_0
  - glib-tools=2.78.4=h6a678d5_0
  - glog=0.5.0=h6a678d5_1
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.14.0=py310h06a4308_0
  - httpcore=1.0.2=py310h06a4308_0
  - httpx=0.27.0=py310h06a4308_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py310h06a4308_0
  - ipython=8.27.0=py310h06a4308_0
  - ipywidgets=8.1.2=py310h06a4308_0
  - jedi=0.19.1=py310h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py310h06a4308_0
  - jsonschema=4.23.0=py310h06a4308_0
  - jsonschema-specifications=2023.7.1=py310h06a4308_0
  - jupyter=1.0.0=py310h06a4308_9
  - jupyter-lsp=2.2.0=py310h06a4308_0
  - jupyter_client=8.6.0=py310h06a4308_0
  - jupyter_console=6.6.3=py310h06a4308_0
  - jupyter_core=5.7.2=py310h06a4308_0
  - jupyter_events=0.10.0=py310h06a4308_0
  - jupyter_server=2.14.1=py310h06a4308_0
  - jupyter_server_terminals=0.4.4=py310h06a4308_1
  - jupyterlab=4.2.5=py310h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py310h06a4308_0
  - jupyterlab_widgets=3.0.10=py310h06a4308_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libabseil=20240116.2=cxx17_h6a678d5_0
  - libboost=1.82.0=h109eef0_2
  - libbrotlicommon=1.0.9=h5eee18b_8
  - libbrotlidec=1.0.9=h5eee18b_8
  - libbrotlienc=1.0.9=h5eee18b_8
  - libclang=14.0.6=default_hc6dbbc7_1
  - libclang13=14.0.6=default_he11475f_1
  - libcups=2.4.2=h2d74bed_1
  - libcurl=8.9.1=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libglib=2.78.4=hdc74915_0
  - libgomp=11.2.0=h1234567_1
  - libgrpc=1.62.2=h2d74bed_0
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.0=hdbd6064_0
  - libprotobuf=4.25.3=he621ea3_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libthrift=0.15.0=h1795dd8_2
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.15=h7f8727e_0
  - libxkbcommon=1.0.1=h097e994_2
  - libxml2=2.13.1=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=2.1.3=py310h5eee18b_0
  - matplotlib-inline=0.1.6=py310h06a4308_0
  - mistune=2.0.4=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_1
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - mpi=1.0=mpich
  - mpi4py=3.1.4=py310hfc96bbd_0
  - mpich=3.3.2=hc856adb_0
  - mysql=8.4.0=h29a9f33_1
  - nbclient=0.8.0=py310h06a4308_0
  - nbconvert=7.16.4=py310h06a4308_0
  - nbformat=5.10.4=py310h06a4308_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - notebook=7.2.2=py310h06a4308_1
  - notebook-shim=0.2.3=py310h06a4308_0
  - numpy=1.26.4=py310h5f9d8c6_0
  - numpy-base=1.26.4=py310hb5e798b_0
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.15=h5eee18b_0
  - orc=2.0.1=h2d29ad5_0
  - overrides=7.4.0=py310h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - prometheus_client=0.21.0=py310h06a4308_0
  - prompt-toolkit=3.0.43=py310h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py310h06a4308_1
  - pyqt=5.15.10=py310h6a678d5_0
  - pyqt5-sip=12.13.0=py310h5eee18b_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - python-fastjsonschema=2.20.0=py310h06a4308_0
  - python-json-logger=2.0.7=py310h06a4308_0
  - pyzmq=25.1.2=py310h6a678d5_0
  - qt-main=5.15.2=hb6262e9_11
  - qtconsole=5.6.0=py310h06a4308_0
  - qtpy=2.4.1=py310h06a4308_0
  - re2=2022.04.01=h295c915_0
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py310h06a4308_0
  - rfc3339-validator=0.1.4=py310h06a4308_0
  - rfc3986-validator=0.1.1=py310h06a4308_0
  - rpds-py=0.10.6=py310hb02cf49_0
  - s2n=1.3.27=hdbd6064_0
  - send2trash=1.8.2=py310h06a4308_0
  - sip=6.7.12=py310h6a678d5_0
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.0=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=py310h06a4308_0
  - tinycss2=1.2.1=py310h06a4308_0
  - tk=8.6.14=h39e8969_0
  - tomli=2.0.1=py310h06a4308_0
  - tornado=6.4.1=py310h5eee18b_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing_extensions=4.11.0=py310h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=1.8.0=py310h06a4308_0
  - widgetsnbextension=4.0.10=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.0.0
      - accelerate==0.24.0
      - aiohttp==3.8.6
      - aiosignal==1.3.1
      - alembic==1.14.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - argparse==1.4.0
      - arrow==1.3.0
      - asteroid-filterbanks==0.4.0
      - async-timeout==4.0.3
      - attrs==23.1.0
      - audioread==3.0.1
      - automat==24.8.1
      - bitsandbytes==0.46.1
      - blobfile==3.0.0
      - boto3==1.37.29
      - botocore==1.37.29
      - cachetools==5.3.2
      - cairocffi==1.7.1
      - cairosvg==2.8.2
      - certifi==2023.7.22
      - cffi==1.16.0
      - charset-normalizer==3.3.1
      - click==8.1.7
      - cmake==3.27.7
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - conformer==0.3.2
      - constantly==23.10.4
      - contourpy==1.3.1
      - cos-python-sdk-v5==1.9.30
      - coscmd==1.8.6.34
      - crcmod==1.7
      - cssselect2==0.8.0
      - cycler==0.12.1
      - dacite==1.9.2
      - datasets==2.14.6
      - datetime==5.5
      - decord==0.6.0
      - deepspeed==0.14.4
      - diffusers==0.23.1
      - dill==0.3.7
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - easydict==1.13
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - eulxml==1.1.3
      - evaluate==0.4.1
      - ffmpeg==1.4
      - filelock==3.13.0
      - fire==0.7.0
      - flash-attn==2.8.1
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fsspec==2023.10.0
      - gcsfs==2024.12.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.24.2
      - google-auth==2.23.3
      - google-auth-oauthlib==1.0.0
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.1.0
      - google-crc32c==1.7.1
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.69.2
      - greenlet==3.1.1
      - grpcio==1.59.0
      - hf-xet==1.1.5
      - hjson==3.1.0
      - htmlmin==0.1.12
      - huggingface-hub==0.33.4
      - humanfriendly==10.0
      - hyperlink==21.0.0
      - hyperpyyaml==1.2.2
      - idna==3.4
      - imagehash==4.3.1
      - immutabledict==4.2.1
      - importlib-metadata==8.7.0
      - incremental==24.7.2
      - isoduration==20.11.0
      - jieba==0.42.1
      - jinja2==3.1.2
      - jiter==0.10.0
      - jiwer==3.0.3
      - jmespath==1.0.1
      - joblib==1.3.2
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - julius==0.2.7
      - kiwisolver==1.4.8
      - lazy-loader==0.3
      - librosa==0.10.1
      - lightning==2.5.0.post0
      - lightning-utilities==0.12.0
      - lit==17.0.3
      - llvmlite==0.41.1
      - loguru==0.7.3
      - lxml==4.9.3
      - mako==1.3.9
      - markdown==3.5
      - markdown-it-py==3.0.0
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - minio==7.2.15
      - mizani==0.13.1
      - more-itertools==10.5.0
      - mpmath==1.3.0
      - msgpack==1.0.7
      - multidict==6.0.4
      - multimethod==1.12
      - multiprocess==0.70.15
      - networkx==3.2.1
      - ninja==1.11.1.1
      - numba==0.58.1
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-ml-py==12.570.86
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu11==11.7.91
      - nvidia-nvtx-cu12==12.4.99
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnxruntime==1.20.1
      - openai==0.28.0
      - openai-whisper==20240930
      - openpyxl==3.1.5
      - optuna==4.2.1
      - packaging==23.2
      - pandas==2.1.2
      - pastel==0.2.1
      - patsy==1.0.1
      - peft==0.6.0
      - phik==0.12.4
      - pillow==11.1.0
      - pip==25.1.1
      - platformdirs==3.11.0
      - plotnine==0.14.5
      - ply==3.11
      - poethepoet==0.10.0
      - pooch==1.8.0
      - portalocker==2.0.0
      - prettytable==3.11.0
      - primepy==1.3
      - proto-plus==1.26.1
      - protobuf==4.24.4
      - psutil==5.9.6
      - puremagic==1.28
      - py-cpuinfo==9.0.0
      - pyannote-core==5.0.0
      - pyannote-database==5.1.3
      - pyannote-metrics==3.2.1
      - pyannote-pipeline==3.0.1
      - pyarrow==19.0.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pycryptodome==3.20.0
      - pycryptodomex==3.23.0
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pydub==0.25.1
      - pymysql==1.1.1
      - pyparsing==3.2.1
      - python-dateutil==2.8.2
      - pytorch-lightning==2.5.0.post0
      - pytorch-metric-learning==2.8.1
      - pytz==2023.3.post1
      - pywavelets==1.8.0
      - pyyaml==6.0.1
      - rapidfuzz==3.4.0
      - regex==2023.10.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - responses==0.18.0
      - rich==13.9.4
      - rouge-chinese==1.0.3
      - rsa==4.9
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.12
      - s3transfer==0.11.4
      - sacrebleu==1.5.1
      - safetensors==0.4.3
      - scikit-learn==1.3.2
      - scipy==1.11.3
      - seaborn==0.12.2
      - semver==3.0.4
      - sentencepiece==0.2.0
      - sentry-sdk==2.24.1
      - setproctitle==1.3.5
      - setuptools==80.9.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sortedcontainers==2.4.0
      - soundfile==0.12.1
      - sox==1.5.0
      - soxr==0.3.7
      - speechbrain==1.0.2
      - sqlalchemy==2.0.38
      - statsmodels==0.14.4
      - sty==1.0.6
      - sympy==1.12
      - tabulate==0.9.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==3.1.0
      - threadpoolctl==3.2.0
      - tiktoken==0.8.0
      - timm==1.0.17
      - tokenizers==0.15.2
      - tomlkit==0.13.3
      - torch==2.4.1+cu124
      - torch-audiomentations==0.12.0
      - torch-pitch-shift==1.2.5
      - torchaudio==2.4.1+cu124
      - torchcde==0.2.5
      - torchdiffeq==0.2.5
      - torchdyn==1.0.6
      - torchmetrics==1.6.1
      - torchsde==0.2.6
      - torchvision==0.19.1
      - tqdm==4.66.1
      - trampoline==0.1.2
      - transformers==4.37.0
      - triton==3.0.0
      - twisted==24.11.0
      - typeguard==4.4.2
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.0
      - typing-inspection==0.4.0
      - tzdata==2023.3
      - ujson==5.10.0
      - uri-template==1.3.0
      - urllib3==2.0.7
      - validators==0.35.0
      - visions==0.8.1
      - wandb==0.19.8
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - werkzeug==3.0.1
      - wget==3.2
      - wheel==0.45.1
      - wordcloud==1.9.4
      - xmltodict==0.13.0
      - xxhash==3.4.1
      - yarl==1.9.2
      - ydata-profiling==4.16.1
      - zipp==3.23.0
      - zope-interface==7.0.3
prefix: /root/autodl-tmp/miniconda3/envs/rt_mo
